### ISSUE TITLE
Piper doesn't see ratbagd

### ISSUE THREAD

**Issue by gorodons** [libratbag/piper#551]
Piper doesn't see ratbagd and crash
**System:** 
NAME="openSUSE Tumbleweed"
VERSION="20200701"
PYTHON VERSION = Python 3.8.3
GNOME VERSION = 3.36.3
**Log:**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/piper/ratbagd.py", line 268, in _on_properties_changed
    object_paths = [d._object_path for d in self._devices]
AttributeError: 'Ratbagd' object has no attribute '_devices'
```

**Comment by stephanlachnit** [comment]
Can you give use your ratbagd version?
```
ratbagd --version
```

**Comment by Username404-59** [comment]
I'm having the exact same issue on openSUSE with piper 0.5.1 and ratbagd 0.15, i think this could be tied to #559

**Comment by sephirot1024** [comment]
Hi, I have the same issue. I am working with openSUSE too, Leap 15.3 in my case.

Fun fact, if i start piper as root, everything works

**Comment by Username404-59** [comment]
#559 mentionned a fix: sudo usermod -a -G games 'YourUserName'

**Comment by mazunki** [comment]
I am having the same problem. Running as root says "No protocol specified" three times, and then a Gtk-WARNING saying it `cannot open display :0`.

Running as usual, gives the aforementioned `_devices` error. I am already in the `games` group, which I had to create with `doas groupadd games`, and I can confirm `/usr/bin/ratbagd` is running at version 0.16. My piper version, from Portage in Gentoo, is 0.5.1-r2.

Any further suggestions?

**Comment by staticssleever668** [comment]
Confirming this issue, if libratbag is built with the `dbus-group` set to something, when user is not in this group, and Piper started when ratabgd is not running yet, an AttributeError is raised.
If you start Piper again, it will show a mouse trap with the expected error message.

Reproducing:
1) Install libratbag compiled with `-Ddbus-group=dummygroupnamefortest`
2) Make sure current user is not in the `dummygroupnamefortest` group
3) Kill ratbagd, e.g. `systemctl stop ratbagd.service`
4) Start Piper through a terminal, see an AttributeError exception raised
5) Start Piper again, see the expected error message.

**Comment by staticssleever668** [comment]
Ignoring the raised exception, the issue here is that the current user is not a part of a needed group. The group is specified by the libratbag package maintainers of distro of choice. So, I suggest checking out distro's wiki or as the last resort check how the distro compiles libratbag, specificaly what it specifies in the `dbus-group` build option.
I will open a separate issue for the exception.
